### ISSUE TITLE
Cannot view tutorials in activator ui

### ISSUE THREAD

**Issue by jeffusan** [typesafehub/activator#1029]
With the 1.3.3 release, I can no longer view local activator template tutorials from the activator ui.

**Comment by henrikengstrom** [comment]
Thanks for reporting @jeffusan. 
Not sure why this is. Meanwhile you can delete your ``~/.activator`` folder to get tutorials to work with 1.3.3.

**Comment by jeffusan** [comment]
Thanks for your reply. 

I deleted ~/.activator and tried again. Unfortunately I have the same results.

In my JavaScript console I see: TypeError: isLocal is not a function

I am running a local tutorial. I have verified that if I install a template from activator, the tutorial works (ie when it is NOT local). But for templates I have downloaded from github (ie local templates), I cannot view the tutorial via activator UI.

**Comment by deanwampler** [comment]
This bug still exists in 1.3.5. Click Tutorial and nothing changes. I also see JS warnings:

```
Uncaught TypeError: Unable to process binding "if: function (){return hasTutorial }"
Message: Unable to process binding "ifnot: function (){return page() }"
Message: Unable to process binding "ifnot: function (){return metaData() }"
Message: Unable to process binding "if: function (){return isLocal() }"
Message: isLocal is not a function
```

I'm not sure which if any occurred before clicking the tutorial link.

**Comment by ketilovre** [comment]
I'm also seeing this error on 1.3.5. Same error output as @deanwampler.

**Comment by nraychaudhuri** [comment]
Encountered the same problem. Local version doesn't work but remote works fine.

**Comment by timcharper** [comment]
^ Please see the pull request; this was an easy fix, innocent mistake.

**Comment by corruptmemory** [comment]
Fix out in 1.3.6

**Comment by timcharper** [comment]
You are rock!!!! Thank you!
